"""create users tables

Revision ID: 0001
Revises: 
Create Date: 2026-02-27 18:56:31.267497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_members',
    sa.Column('company_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='companyrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'member_id')
    )
    with op.batch_alter_table('company_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_invitations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_invitations_id'))

    op.drop_table('company_members')
    # ### end Alembic commands ###
