"""create quiz workflow table

Revision ID: 0006
Revises: 0005
Create Date: 2026-03-04 02:39:48.385216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_workflow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_workflow_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_workflow_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_workflow_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_workflow_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('quiz_answer_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_provider_provider_id', ['provider', 'provider_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provider_provider_id', type_='unique')

    with op.batch_alter_table('quiz_answer_options', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('quiz_workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_workflow_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_workflow_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_workflow_company_id'))

    op.drop_table('quiz_workflow')
    # ### end Alembic commands ###
